### ISSUE TITLE
if u see this question,please reply me~~~

### ISSUE THREAD

**Issue by SaltyFishhh** [ZJZAC/Passport-aware-Normalization#1]
作者您好，在复现您的代码有些小问题向您咨询，在classification_private.py文件中，For ambiguity，from amb_attack import train_maximize, test_fake，amb_attack这个module是在哪里？

**Comment by ZJZAC** [comment]
It is same with the script under /Image_cls/Baseline/amb_attack.py. 
Nevertheless, we add it into the path /Image_cls/Ours/
